# Setup
title: 益谦YiQian
description: 我们以渺小来爱这个巨大的世界 / We love this vast world with our smallness.
url: https://cat.you7n.com
avatar: /avatar.png
paginate: 5
permalink: pretty
cover_image: /bg2.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username:  
  card: summary
logo: logo.png
social:
  name: YiQian
  links:
    - https://github.com/mickeyyqa
    - https://mp.weixin.qq.com/mp/profile_ext?action=home&__biz=MzkyMTYwMTIzNQ==&scene=124#wechat_redirect
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: you7n
  url: https://cat.you7n.com
  email: qiaoyang172@163.com
